version: "3.9"
services:
  test-orchestrator:
    build:
      context: .
      dockerfile: test-orchestrator/Dockerfile
    volumes:
      - gradle-cache:/root/.gradle
      - ./allure-results:/tmp/allure-results
    ports:
      - "5050:35277"
    environment:
      GRADLE_USER_HOME: /root/.gradle
#    command: ["sleep", "infinity"]
volumes:
  gradle-cache:
